    version: 2
    updates:
      - package-ecosystem: "pip"
        directory: "/" 
        schedule:
          interval: "daily"
        allow:
          - dependency-name: "pygame-ce"
          - dependency-name: "moderngl"
          - dependency-name: "asyncio"
          - dependency-name: "uuid"
          - dependency-name: "numpy"
          - dependency-name: "supabase"